# Generated by Django 3.2.3 on 2022-01-02 17:27

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nama', models.CharField(max_length=50)),
                ('is_staff', models.BooleanField(default=False, help_text='Menentukan apakah user merupakan Staff', verbose_name='Status Staff')),
                ('is_esp', models.BooleanField(default=False, help_text='Menentukan apakah user merupakan Bendahara', verbose_name='Status Bendahara')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BulanTahun',
            fields=[
                ('id_bulan_tahun', models.BigAutoField(default=None, primary_key=True, serialize=False)),
                ('tahun', models.IntegerField()),
                ('bulan', models.CharField(choices=[('1', 'Januari'), ('2', 'Februari'), ('3', 'Maret'), ('4', 'April'), ('5', 'Mei'), ('6', 'Juni'), ('7', 'Juli'), ('8', 'Agustus'), ('9', 'September'), ('10', 'Oktober'), ('11', 'November'), ('12', 'Desember')], default='1', max_length=2)),
            ],
            options={
                'unique_together': {('bulan', 'tahun')},
            },
        ),
        migrations.CreateModel(
            name='Jabatan',
            fields=[
                ('id_jabatan', models.BigAutoField(primary_key=True, serialize=False)),
                ('nama_jabatan', models.CharField(max_length=50)),
                ('gaji_pokok', models.PositiveIntegerField()),
                ('satuan_gaji', models.CharField(choices=[('1', 'Jam'), ('2', 'Bulan'), ('3', 'Pertemuan')], default='1', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jurusan',
            fields=[
                ('id_jurusan', models.BigAutoField(primary_key=True, serialize=False)),
                ('jurusan', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('nupy', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nama_pegawai', models.CharField(max_length=50)),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('tempat_lahir', models.CharField(max_length=50)),
                ('tanggal_lahir', models.DateField()),
                ('alamat', models.TextField()),
                ('no_telpon', models.CharField(max_length=13)),
                ('tanggal_masuk', models.DateField()),
                ('foto', models.ImageField(upload_to='fotopegawai/')),
                ('ket_pegawai', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pendidikan',
            fields=[
                ('id_pendidikan', models.BigAutoField(primary_key=True, serialize=False)),
                ('pendidikan', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Surat_mutasi_jabatan',
            fields=[
                ('sk_mutasi_jabatan', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tanggal_mutasi_jabatan', models.DateField()),
                ('ket_mutasi_jabatan', models.TextField()),
                ('file_surat', models.FileField(upload_to='suratmutasijabatan/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Universitas',
            fields=[
                ('id_universitas', models.BigAutoField(primary_key=True, serialize=False)),
                ('universitas', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Riwayat_pendidikan',
            fields=[
                ('id_riwayat_pendidikan', models.BigAutoField(default=None, primary_key=True, serialize=False)),
                ('tahun_lulus', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jurusan', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='kepegawaian.jurusan')),
                ('nupy', models.ForeignKey(db_column='nupy', on_delete=django.db.models.deletion.CASCADE, to='kepegawaian.pegawai')),
                ('pendidikan', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='kepegawaian.pendidikan')),
                ('universitas', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='kepegawaian.universitas')),
            ],
            options={
                'unique_together': {('nupy', 'pendidikan', 'jurusan', 'universitas')},
            },
        ),
        migrations.CreateModel(
            name='Gaji_kualitas',
            fields=[
                ('id_gaji_kualitas', models.BigAutoField(default=None, primary_key=True, serialize=False)),
                ('ekskul', models.IntegerField(default=None)),
                ('kinerja', models.IntegerField()),
                ('tunjangan', models.IntegerField()),
                ('ket_gaji', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bulantahun', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='kepegawaian.bulantahun')),
                ('nupy', models.ForeignKey(db_column='nupy', on_delete=django.db.models.deletion.CASCADE, to='kepegawaian.pegawai')),
            ],
            options={
                'unique_together': {('nupy', 'bulantahun')},
            },
        ),
        migrations.CreateModel(
            name='Gaji_jabatan',
            fields=[
                ('id_gaji_jabatan', models.BigAutoField(default=None, primary_key=True, serialize=False)),
                ('kuantitas', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bulantahun', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='kepegawaian.bulantahun')),
                ('jabatan', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='kepegawaian.jabatan')),
                ('nupy', models.ForeignKey(db_column='nupy', on_delete=django.db.models.deletion.CASCADE, to='kepegawaian.pegawai')),
            ],
            options={
                'unique_together': {('nupy', 'jabatan', 'bulantahun')},
            },
        ),
        migrations.CreateModel(
            name='Detail_jabatan',
            fields=[
                ('id_detail_jabatan', models.BigAutoField(default=None, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_jabatan', models.CharField(choices=[('1', 'Aktif'), ('2', 'Non Aktif')], default='1', max_length=1)),
                ('jabatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kepegawaian.jabatan')),
                ('nupy', models.ForeignKey(db_column='nupy', on_delete=django.db.models.deletion.CASCADE, to='kepegawaian.pegawai')),
                ('sk_mutasi_jabatan', models.ForeignKey(db_column='sk_mutasi_jabatan', null=True, on_delete=django.db.models.deletion.CASCADE, to='kepegawaian.surat_mutasi_jabatan')),
            ],
            options={
                'unique_together': {('nupy', 'sk_mutasi_jabatan', 'jabatan')},
            },
        ),
    ]
