# Generated by Django 3.2.3 on 2021-06-22 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kepegawaian', '0002_auto_20210622_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulanTahun',
            fields=[
                ('id_bulan_tahun', models.BigAutoField(default=None, primary_key=True, serialize=False)),
                ('tahun', models.IntegerField()),
                ('bulan', models.CharField(choices=[('1', 'Januari'), ('2', 'Februari'), ('3', 'Maret'), ('4', 'April'), ('5', 'Mei'), ('6', 'Juni'), ('7', 'Juli'), ('8', 'Agustus'), ('9', 'September'), ('10', 'Oktober'), ('11', 'November'), ('12', 'Desember')], default='1', max_length=2)),
            ],
            options={
                'unique_together': {('bulan', 'tahun')},
            },
        ),
        migrations.AddField(
            model_name='gaji',
            name='bulantahun',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='kepegawaian.bulantahun'),
        ),
        migrations.AlterUniqueTogether(
            name='gaji',
            unique_together={('nupy', 'bulantahun')},
        ),
        migrations.RemoveField(
            model_name='gaji',
            name='bulan',
        ),
        migrations.RemoveField(
            model_name='gaji',
            name='tahun',
        ),
    ]
