# Generated by Django 3.2.3 on 2021-06-22 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kepegawaian', '0003_auto_20210622_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaji',
            name='jabatan',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='kepegawaian.jabatan'),
        ),
    ]
