# Generated by Django 3.2.3 on 2021-06-23 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kepegawaian', '0004_gaji_jabatan'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gaji',
            unique_together={('nupy', 'jabatan', 'bulantahun')},
        ),
    ]
