# Generated by Django 3.2.3 on 2021-07-07 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kepegawaian', '0005_alter_gaji_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tanggal_absen',
            name='Tanggal_absen',
        ),
        migrations.AddField(
            model_name='tanggal_absen',
            name='tanggal_absen',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='absensi',
            name='status_absen',
            field=models.CharField(choices=[('H', 'Hadir'), ('I', 'Izin'), ('S', 'Sakit'), ('A', 'Absen')], default='-', max_length=1),
        ),
    ]
