# Generated by Django 3.2.3 on 2021-07-12 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kepegawaian', '0006_auto_20210707_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jabatan',
            name='nama_jabatan',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='jurusan',
            name='jurusan',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lembaga',
            name='nama_lembaga',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pegawai',
            name='nupy',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pegawai',
            name='tempat_lahir',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pendidikan',
            name='pendidikan',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='surat_cuti',
            name='no_surat',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='surat_mutasi_jabatan',
            name='sk_mutasi_jabatan',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='surat_mutasi_keluar',
            name='sk_mutasi_keluar',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='surat_pensiun',
            name='sk_pensiun',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='universitas',
            name='universitas',
            field=models.CharField(max_length=50),
        ),
    ]
