# Generated by Django 3.2.3 on 2021-07-12 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kepegawaian', '0007_auto_20210712_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riwayat_pendidikan',
            name='tahun_lulus',
            field=models.DateField(null=True),
        ),
    ]
