# Generated by Django 3.2.3 on 2021-07-12 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kepegawaian', '0008_alter_riwayat_pendidikan_tahun_lulus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riwayat_pendidikan',
            name='tahun_lulus',
            field=models.DateField(),
        ),
    ]
