# Generated by Django 3.2.3 on 2021-07-12 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kepegawaian', '0009_alter_riwayat_pendidikan_tahun_lulus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pegawai',
            name='alamat',
            field=models.TextField(),
        ),
    ]
