# Generated by Django 3.2.3 on 2021-10-05 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kepegawaian', '0012_alter_riwayat_pendidikan_tahun_lulus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riwayat_pendidikan',
            name='tahun_lulus',
            field=models.DateField(blank=True, null=True),
        ),
    ]
