# Generated by Django 3.2.3 on 2021-10-05 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kepegawaian', '0013_alter_riwayat_pendidikan_tahun_lulus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riwayat_pendidikan',
            name='jurusan',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='kepegawaian.jurusan'),
        ),
        migrations.AlterField(
            model_name='riwayat_pendidikan',
            name='pendidikan',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='kepegawaian.pendidikan'),
        ),
        migrations.AlterField(
            model_name='riwayat_pendidikan',
            name='universitas',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='kepegawaian.universitas'),
        ),
    ]
