# Generated by Django 3.2.3 on 2021-10-07 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kepegawaian', '0014_auto_20211005_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gaji_jabatan',
            fields=[
                ('id_gaji_jabatan', models.BigAutoField(default=None, primary_key=True, serialize=False)),
                ('kuantitas', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bulantahun', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='kepegawaian.bulantahun')),
                ('jabatan', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='kepegawaian.jabatan')),
                ('nupy', models.ForeignKey(db_column='nupy', on_delete=django.db.models.deletion.CASCADE, to='kepegawaian.pegawai')),
            ],
            options={
                'unique_together': {('nupy', 'jabatan', 'bulantahun')},
            },
        ),
        migrations.CreateModel(
            name='Gaji_kualitas',
            fields=[
                ('id_gaji_kualitas', models.BigAutoField(default=None, primary_key=True, serialize=False)),
                ('ekskul', models.IntegerField(default=None)),
                ('kinerja', models.IntegerField()),
                ('tunjangan', models.IntegerField()),
                ('ket_gaji', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bulantahun', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='kepegawaian.bulantahun')),
                ('nupy', models.ForeignKey(db_column='nupy', on_delete=django.db.models.deletion.CASCADE, to='kepegawaian.pegawai')),
            ],
            options={
                'unique_together': {('nupy', 'bulantahun')},
            },
        ),
        migrations.DeleteModel(
            name='Gaji',
        ),
    ]
