# Generated by Django 3.2.3 on 2021-10-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kepegawaian', '0015_auto_20211008_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='jabatan',
            name='satuan_gaji',
            field=models.CharField(choices=[('1', 'Jam'), ('2', 'Bulan'), ('3', 'Pertemuan')], default='1', max_length=1),
        ),
    ]
