# Generated by Django 3.2.3 on 2021-11-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kepegawaian', '0016_jabatan_satuan_gaji'),
    ]

    operations = [
        migrations.AddField(
            model_name='surat_mutasi_jabatan',
            name='file_surat',
            field=models.FileField(default=None, upload_to='suratmutasijabatan/'),
            preserve_default=False,
        ),
    ]
